  # Este archivo sirve para crear registros de prueba
Task.create(task_name:'Hacer el super',  name: "Irene Suarez")
Task.create(task_name:'Independizar a México',  name: "Benito Juarez")
Task.create(task_name:'Corregir el código',  name: "André Hernández")
Task.create(task_name:'Ir a la fiesta',  name: "Vasco Rosado")
Task.create(task_name:'Pintar el carro',  name: "Jesus Madero")
Task.create(task_name:'Evangelizar el mundo',  name: "Jesus de Nazaret")
Task.create(task_name:'Robar el termostato de 12999 WATTS',  name: "Juan López")
Task.create(task_name:'Conducir el tractor',  name: "Miguel Barragan")
Task.create(task_name:'Construir la maqueta',  name: "Mauricio Suastegui")
Task.create(task_name:'Hacer los examenes',  name: "Alonso Martinez")
Task.create(task_name:'Tender la ropa',  name: "Melchor Benitez")
Task.create(task_name:'Industrializar a México',  name: "Porfirio Díaz")
Task.create(task_name:'Prender la luz',  name: "Ambar Rived")
Task.create(task_name:'Tocar la gutarra',  name: "Ana Urbina")
Task.create(task_name:'Cocinar el pollo',  name: "Aitana Garcia")