tag1 = Tag.create(name: "Medicine")
tag2 = Tag.create(name: "Global News")
tag3 = Tag.create(name: "Politics")
tag4 = Tag.create(name: "Animals")
tag5 = Tag.create(name: "Products")
tag6 = Tag.create(name: "Artists")

post1 = Post.create(title: "The death", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sagittis dui tortor, vel vehicula est facilisis vitae. Sed consectetur consequat euismod. Nam eu nunc ut purus venenatis congue id id metus. Phasellus a cursus justo. Nunc vitae varius elit. Duis consectetur et lacus ac sollicitudin. Sed feugiat tellus eu dui ultricies, quis venenatis leo posuere. Nunc pulvinar orci a sem semper fringilla. Suspendisse non luctus purus, eu fringilla sem. Sed facilisis tellus vitae pellentesque luctus. Ut commodo tellus a augue commodo, et consequat dui aliquet. Aenean accumsan elit sit amet dui venenatis, et porta neque fringilla.

Sed blandit faucibus malesuada. Ut interdum commodo facilisis. Nam egestas lectus a congue imperdiet. Quisque eget ante eu mi molestie varius eu sit amet urna. Nulla libero dolor, eleifend interdum congue id, convallis at ante. Fusce sit amet lectus sodales, dignissim felis sit amet, tincidunt nulla. Nulla facilisi. Ut vestibulum sem sed enim auctor, dapibus hendrerit ex tempor. Sed non malesuada velit. Ut porta euismod eros, ut tincidunt sem.

Aliquam erat volutpat. In sed gravida purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc urna eros, feugiat sed luctus vel, dignissim eget nunc. Praesent nisl lectus, gravida sit amet consectetur vitae, venenatis sit amet orci. Praesent euismod lectus eget euismod vulputate. Mauris rutrum in ligula a vestibulum.

Ut interdum dapibus diam quis porta. Suspendisse posuere luctus lectus, eu pulvinar orci lobortis in. Fusce viverra lacinia ligula, vitae fermentum quam pulvinar tempor. Integer euismod nisl libero, vitae tincidunt dui placerat at. Praesent feugiat scelerisque dui, id molestie neque semper sit amet. Quisque ut auctor arcu. Maecenas non finibus neque. In accumsan eget sem sit amet bibendum. Curabitur suscipit, mi a vulputate blandit, neque enim finibus nisi, non placerat leo urna ac elit. Donec luctus sagittis nibh, vitae eleifend orci scelerisque aliquam. Aenean auctor neque gravida, facilisis tellus a, dictum eros. Sed bibendum justo neque, sit amet commodo ipsum laoreet non. Maecenas lacinia, ex non rutrum viverra, libero lectus aliquet ante, in mollis ipsum purus sit amet enim. In leo nibh, scelerisque vitae nunc nec, consequat tincidunt massa. Donec quis dui varius, cursus orci sit amet, pellentesque felis." )

post2 = Post.create(title: "About animals...", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sagittis dui tortor, vel vehicula est facilisis vitae. Sed consectetur consequat euismod. Nam eu nunc ut purus venenatis congue id id metus. Phasellus a cursus justo. Nunc vitae varius elit. Duis consectetur et lacus ac sollicitudin. Sed feugiat tellus eu dui ultricies, quis venenatis leo posuere. Nunc pulvinar orci a sem semper fringilla. Suspendisse non luctus purus, eu fringilla sem. Sed facilisis tellus vitae pellentesque luctus. Ut commodo tellus a augue commodo, et consequat dui aliquet. Aenean accumsan elit sit amet dui venenatis, et porta neque fringilla.

Sed blandit faucibus malesuada. Ut interdum commodo facilisis. Nam egestas lectus a congue imperdiet. Quisque eget ante eu mi molestie varius eu sit amet urna. Nulla libero dolor, eleifend interdum congue id, convallis at ante. Fusce sit amet lectus sodales, dignissim felis sit amet, tincidunt nulla. Nulla facilisi. Ut vestibulum sem sed enim auctor, dapibus hendrerit ex tempor. Sed non malesuada velit. Ut porta euismod eros, ut tincidunt sem.

Aliquam erat volutpat. In sed gravida purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc urna eros, feugiat sed luctus vel, dignissim eget nunc. Praesent nisl lectus, gravida sit amet consectetur vitae, venenatis sit amet orci. Praesent euismod lectus eget euismod vulputate. Mauris rutrum in ligula a vestibulum.

Ut interdum dapibus diam quis porta. Suspendisse posuere luctus lectus, eu pulvinar orci lobortis in. Fusce viverra lacinia ligula, vitae fermentum quam pulvinar tempor. Integer euismod nisl libero, vitae tincidunt dui placerat at. Praesent feugiat scelerisque dui, id molestie neque semper sit amet. Quisque ut auctor arcu. Maecenas non finibus neque. In accumsan eget sem sit amet bibendum. Curabitur suscipit, mi a vulputate blandit, neque enim finibus nisi, non placerat leo urna ac elit. Donec luctus sagittis nibh, vitae eleifend orci scelerisque aliquam. Aenean auctor neque gravida, facilisis tellus a, dictum eros. Sed bibendum justo neque, sit amet commodo ipsum laoreet non. Maecenas lacinia, ex non rutrum viverra, libero lectus aliquet ante, in mollis ipsum purus sit amet enim. In leo nibh, scelerisque vitae nunc nec, consequat tincidunt massa. Donec quis dui varius, cursus orci sit amet, pellentesque felis.")

post3 = Post.create(title: "Milenials", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sagittis dui tortor, vel vehicula est facilisis vitae. Sed consectetur consequat euismod. Nam eu nunc ut purus venenatis congue id id metus. Phasellus a cursus justo. Nunc vitae varius elit. Duis consectetur et lacus ac sollicitudin. Sed feugiat tellus eu dui ultricies, quis venenatis leo posuere. Nunc pulvinar orci a sem semper fringilla. Suspendisse non luctus purus, eu fringilla sem. Sed facilisis tellus vitae pellentesque luctus. Ut commodo tellus a augue commodo, et consequat dui aliquet. Aenean accumsan elit sit amet dui venenatis, et porta neque fringilla.

Sed blandit faucibus malesuada. Ut interdum commodo facilisis. Nam egestas lectus a congue imperdiet. Quisque eget ante eu mi molestie varius eu sit amet urna. Nulla libero dolor, eleifend interdum congue id, convallis at ante. Fusce sit amet lectus sodales, dignissim felis sit amet, tincidunt nulla. Nulla facilisi. Ut vestibulum sem sed enim auctor, dapibus hendrerit ex tempor. Sed non malesuada velit. Ut porta euismod eros, ut tincidunt sem.

Aliquam erat volutpat. In sed gravida purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc urna eros, feugiat sed luctus vel, dignissim eget nunc. Praesent nisl lectus, gravida sit amet consectetur vitae, venenatis sit amet orci. Praesent euismod lectus eget euismod vulputate. Mauris rutrum in ligula a vestibulum.

Ut interdum dapibus diam quis porta. Suspendisse posuere luctus lectus, eu pulvinar orci lobortis in. Fusce viverra lacinia ligula, vitae fermentum quam pulvinar tempor. Integer euismod nisl libero, vitae tincidunt dui placerat at. Praesent feugiat scelerisque dui, id molestie neque semper sit amet. Quisque ut auctor arcu. Maecenas non finibus neque. In accumsan eget sem sit amet bibendum. Curabitur suscipit, mi a vulputate blandit, neque enim finibus nisi, non placerat leo urna ac elit. Donec luctus sagittis nibh, vitae eleifend orci scelerisque aliquam. Aenean auctor neque gravida, facilisis tellus a, dictum eros. Sed bibendum justo neque, sit amet commodo ipsum laoreet non. Maecenas lacinia, ex non rutrum viverra, libero lectus aliquet ante, in mollis ipsum purus sit amet enim. In leo nibh, scelerisque vitae nunc nec, consequat tincidunt massa. Donec quis dui varius, cursus orci sit amet, pellentesque felis.")

post4 = Post.create(title: "Trump and his stupidity...", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sagittis dui tortor, vel vehicula est facilisis vitae. Sed consectetur consequat euismod. Nam eu nunc ut purus venenatis congue id id metus. Phasellus a cursus justo. Nunc vitae varius elit. Duis consectetur et lacus ac sollicitudin. Sed feugiat tellus eu dui ultricies, quis venenatis leo posuere. Nunc pulvinar orci a sem semper fringilla. Suspendisse non luctus purus, eu fringilla sem. Sed facilisis tellus vitae pellentesque luctus. Ut commodo tellus a augue commodo, et consequat dui aliquet. Aenean accumsan elit sit amet dui venenatis, et porta neque fringilla.

Sed blandit faucibus malesuada. Ut interdum commodo facilisis. Nam egestas lectus a congue imperdiet. Quisque eget ante eu mi molestie varius eu sit amet urna. Nulla libero dolor, eleifend interdum congue id, convallis at ante. Fusce sit amet lectus sodales, dignissim felis sit amet, tincidunt nulla. Nulla facilisi. Ut vestibulum sem sed enim auctor, dapibus hendrerit ex tempor. Sed non malesuada velit. Ut porta euismod eros, ut tincidunt sem.

Aliquam erat volutpat. In sed gravida purus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc urna eros, feugiat sed luctus vel, dignissim eget nunc. Praesent nisl lectus, gravida sit amet consectetur vitae, venenatis sit amet orci. Praesent euismod lectus eget euismod vulputate. Mauris rutrum in ligula a vestibulum.

Ut interdum dapibus diam quis porta. Suspendisse posuere luctus lectus, eu pulvinar orci lobortis in. Fusce viverra lacinia ligula, vitae fermentum quam pulvinar tempor. Integer euismod nisl libero, vitae tincidunt dui placerat at. Praesent feugiat scelerisque dui, id molestie neque semper sit amet. Quisque ut auctor arcu. Maecenas non finibus neque. In accumsan eget sem sit amet bibendum. Curabitur suscipit, mi a vulputate blandit, neque enim finibus nisi, non placerat leo urna ac elit. Donec luctus sagittis nibh, vitae eleifend orci scelerisque aliquam. Aenean auctor neque gravida, facilisis tellus a, dictum eros. Sed bibendum justo neque, sit amet commodo ipsum laoreet non. Maecenas lacinia, ex non rutrum viverra, libero lectus aliquet ante, in mollis ipsum purus sit amet enim. In leo nibh, scelerisque vitae nunc nec, consequat tincidunt massa. Donec quis dui varius, cursus orci sit amet, pellentesque felis.")
#**************************************************************#
relation1 = Relation.create(post_id: post3.id, tag_id: tag1.id)
relation2 = Relation.create(post_id: post1.id, tag_id: tag1.id)
relation3 = Relation.create(post_id: post2.id, tag_id: tag2.id)
relation4 = Relation.create(post_id: post3.id, tag_id: tag2.id)
relation5 = Relation.create(post_id: post4.id, tag_id: tag3.id)
relation6 = Relation.create(post_id: post3.id, tag_id: tag4.id)
relation7 = Relation.create(post_id: post2.id, tag_id: tag5.id)
relation8 = Relation.create(post_id: post4.id, tag_id: tag6.id)
